---
title: "Introduction"
format: html
---

## Objectives
- Understand the scope and expectations of the course.  
- Preview themes: international trade, finance, global issues.  
- Situate Japan in the world economy.  

## Key Concepts
- Japan's economic scale and structure: GDP size and growth trends relative to other major economies.
- Demographic trend: an aging, shrinking population and its long-term economic implications.
- Trade dependence: reliance on trade and integration into global supply chains.
 

## Readings
- Ito and Hoshi (2020), chapter 1-3 

## Data
- MPD version 2023: Bolt, Jutta and Jan Luiten van Zanden (2024). Maddison style estimates of the evolution of the world economy: A new 2023 update. Journal of Economic Surveys, 1–41. DOI: 10.1111/joes.12618
- Feenstra, Robert C., Robert Inklaar and Marcel P. Timmer (2015), "The Next Generation of the Penn World Table" American Economic Review, 105(10), 3150-3182, available for download at www.ggdc.net/pwt


## Materials
- **Slides** [View Slides](../slides/01_intro.html)  


