---
title: "Measurement of Global Value Chains"
format: html
---

## Objectives
- Definition of Global Value Chains
- How to measure GVC, including the use of input-output tables

## Key Concepts
- Trade in value added
- Backward and forward participation in GVCs

## Readings
- Baldwin, R., & Ito, T. (2021). The smile curve: Evolving sources of value added in manufacturing. Canadian Journal of Economics/Revue Canadienne d’économique, 54(4), 1842–1880. 
- Elms, D. K., & Low, P. (2013). Global value chains in a changing world. World trade organization.
- Suvannaphakdy, S., & Pham, T. P. T. (2023). GVC Reconfiguration. ISEAS–Yusof Ishak Institute Singapore.
- WTO and JETRO-IDE (2011), Trade patterns and global value chains in East Asia: from trade in goods to trade in tasks. 
- Xing, Y., and N. Detert (2010). How the iPhone Widens the United States Trade Deficit with the People’s Republic of China. ADBI Working Paper 257. Tokyo: Asian Development Bank.

## Data
- Mancini, M., & Taglioni, D. (2025). Economic consequences of trade and global value chain integration: A measurement perspective. The World Bank Economic Review, https://doi.org/10.1093/wber/lhaf017.

## Materials
- **Slides:** [View Slides](slides/02_gvc.qmd)  
