---
title: "Cross-border investment"
format: html
---

## Objectives
- Examine outward foreign direct investment (FDI) trends in ASEAN's manufacturing and services sectors
- Identify barriers to inward FDI
- Compare commercial and strategic investment logic against official development assistance (ODA)


## Key Concepts 
- Foreign Direct Investment (FDI)
- Mergers & Acquisitions (M&A)
- Multinational Enterprises (MNEs)
 
## Suggested Reading
- Alfaro, L., & Charlton, A. (2009). Intra-Industry Foreign Direct Investment. American Economic Review, 99(5), 2096–2119. https://doi.org/10.1257/aer.99.5.2096
- Antràs, P., & Yeaple, S. R. (2014). Multinational Firms and the Structure of International Trade. In Handbook of International Economics (Vol. 4, pp. 55–130). Elsevier. https://linkinghub.elsevier.com/retrieve/pii/B9780444543141000021
- Baldwin, R., & Okubo, T. (2014). Networked FDI: Sales and Sourcing Patterns of Japanese Foreign Affiliates. The World Economy, 37(8), 1051–1080. https://doi.org/10.1111/twec.12116
- Blonigen, B. A., Davies, R. B., Waddell, G. R., & Naughton, H. T. (2007). FDI in space: Spatial autoregressive relationships in foreign direct investment. European Economic Review, 51(5), 1303–1325. https://doi.org/10.1016/j.euroecorev.2006.08.006
- Cieślik, A., & Ryan, M. (2004). Explaining Japanese direct investment flows into an enlarged Europe: A comparison of gravity and economic potential approaches. Journal of the Japanese and International Economies, 18(1), 12–37. https://doi.org/10.1016/j.jjie.2003.09.009
- Hoshi T. (2018). Has Abenomics succeeded in raising Japan's inward Foreign Direct Investment? Asian Economic Policy Review, 13 (1), 149–168.

## Materials
- **Slides:** [View Slides](../slides/06_fdi.html)  

